name 'chef_workstation'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef_workstation'
long_description 'Installs/Configures chef_workstation'
version '0.1.0'
