name 'store-test-automation'
maintainer 'Andrew S thompson'
maintainer_email 'admin@entercloud.info'
license 'all_rights'
description 'Installs/Configures store-test-automation depencdenies for the build machine'
long_description 'Installs/Configures store-test-automation - install array of required packages and creates the file structure for CI '
version '1.0.0'
